### PR TITLE
Don't ignore example pdfs

### PR DESCRIPTION
**Pull request by Giebisch**
I think it's good practice to include example pdfs for the given .tex examples.
This is the first thing new users look at when visiting the repo

### CODE REVIEW

**Comment by passamo9** [comment]
Yeah, I think that I would definitely also prefer to see that.

I also have some difficulty with the code that I merged earlier - tried copying and pasting it in MacTeX, but it didn't work?

**Comment by Giebisch** [comment]
> I also have some difficulty with the code that I merged earlier - tried copying and pasting it in MacTeX, but it didn't work?
What's the problem ? Maybe create an issue

**Comment by yjyao** [comment]
i think the best practice would be to use a CI to auto-refresh the PDFs, instead of including them as part of the repo (and requiring the contributors to remember updating the PDFs when commiting). with a quick googling i found github.com/xu-cheng/latex-action and github.com/sharelatex/github-latex-ci which could be useful.

**Comment by passamo9** [comment]
@yjyao

What do these two compilers do?

Which one do you suggest?

**Comment by yjyao** [comment]
> What do these two compilers do?

they are not "compilers."

the idea is called Continuous Integration (CI) apparently on Github it's call an "Github Action." whenever you commit/submit new code, a series of actions will automatically run. you can add tests to make sure your code did not break anything. or in this case, you can make it compile all the example docs every time someone commits some code. the benefits are:

1. the PDF previews will always be up to date. you won't "forget" to update the examples in your commits.
2. with the current approach, since the PDFs are checked in to the same branch, if two people contributed at the same time (like PRs #7 and #10), the example PDFs will have conflicts and the PR authors will have to resolve them manually, which is annoying.

> Which one do you suggest?

i experimented last night and was able to get this: https://github.com/yjyao/githubactions-test.

in the main page / README you can see a link saying "here," it brings you to a list of PDF previews:
image

the PDF previews are automatically generated after each commit, as you can see in the Actions tab:
image

@Giebisch what do you think / how would you compare the two approaches?

@passamo9 i can help set this up but you will need to create an empty branch first. if you don't know how you can add me as a collaborator (repo main page -> settings -> manage access -> invite collaborator). note this **grants me permission to directly change your repo** so it could be dangerous.

**Comment by passamo9** [comment]
>so it could be dangerous

If you decide to burn everything down 😂

I trust you insofar as I wouldn't have been able to do anything without you and the others! Risk I'm willing to take

**Comment by passamo9** [comment]
What gives??

image

**Comment by yjyao** [comment]
apparently i don't exist lol. i think you drop the `@`? anyways i want to get @Giebisch's opinion on this before we move on. so could you hold it off for now?

**Comment by passamo9** [comment]
Yes, it's time you took off your invisibility cloak!

No worries, I'll wait for when you're both in agreement.

**Comment by Giebisch** [comment]
> @Giebisch what do you think / how would you compare the two approaches?

That seems like a great idea ! I've actually never used Github Actions to create PDFs, but seems to work easy enough. Do it ;)

**Comment by yjyao** [comment]
ok then. @passamo9 can you try inviting me again?

**Comment by passamo9** [comment]
You should be golden

**Pull request merged**
