### PR TITLE
Add opinion.tex to latexmk ci.

### PR DESCRIPTION
**Pull request by yjyao**

### CODE REVIEW

**Comment by bond7o6** [comment]
Is there a way for it to just build all .tex files in the repo?

**Comment by yjyao** [comment]
i wish. haven't found a way yet. i was thinking maybe add a pre submit hook that reminds people to edit the yml?

**Comment by bond7o6** [comment]
Could definitely do that, also maybe write a collab.md at some point with that in there. The pre-submit hook is probably the way to go for know though.

**Review by bond7o6 — APPROVED** [review]

**Comment by passamo9** [comment]
@yjyao @bond7o6 Can I be of help here?

**Comment by yjyao** [comment]
you can merge : )

or if you trust me enough and are bothered with too many PRs going on, since i have commit access, i can merge myself (after getting an approval) going forward. for now i'm restraining myself from clicking that tempting green button : )

**Comment by passamo9** [comment]
You show an incredible amount of restraint! I hope I am not slowing you down. If I accept the PRs, there's a certain amount of control that I keep (kind of like the commander in chief is a civilian) which means that as a non-expert (lawyer) I can hopefully keep up insofar as it's possible and be able to sell it the most to bar association or what have you. I really appreciate so much the amount of time that you and everyone else is spending on this. It's fascinating to see your work!

**Pull request merged**
