### PR TITLE
Add \maketitle for engwales-plead

### PR DESCRIPTION
**Pull request by yjyao**
This aims to replicate "Particulars of Claim, first page.docx."

I wasn't sure whether the "Particulars of claim" was part of the title (or just a section name) so I left it out of the command and it is currently *unformatted*.

Preview: 
image

### CODE REVIEW

**Comment by passamo9** [comment]
This is great!

If possible, could you put the Particulars of Claim in the Tram Lines?
image

Would this work?
`\centerline{\vbox {\hrule \vskip 12pt \hbox {\hskip 12pt Particulars of Claim \hskip 12pt } \vskip 12pt \hrule }}`

**Comment by yjyao** [comment]
is "Particulars of Claim" part of the title (i'm guessing yes)?

**Comment by passamo9** [comment]
It's the title of the type of pleading.

If this isn't helpful, how can I understand your question better?

**Comment by yjyao** [comment]
yes that answers the question. so it's a type of pleading. do other types of pleading have the same format (except for the title text)?

**Comment by passamo9** [comment]
Yes, that's correct.

The other example that I used was Defence and Counterclaim, which only needs a bold centred section title "Counterclaim" to be added for that section of the pleadings.

The last thing I have to sort out for the particulars of claim is the final sections, which need to include cases in which negligence is pleaded (not complex) a prayer for relief (short statement) and this is basically done.

Thank you so much!

**Comment by yjyao** [comment]
cool i saw your ["Skeleton Argument Template, first pages.docx"](https://github.com/passamo9/LaTeX_EnglandWales_Templates/blob/main/Skeleton%20Argument%20Template%2C%20first%20pages.docx) has (almost) the same layout as this is. i'll make `\title` available to set the title then.

**Comment by passamo9** [comment]
Yeah, it's the same heading but it's a different format in the body.
The Paragraphs have numbering 1., 1.1., 1.2.
Like this one, I will be able to add more detail to the Skeleton as soon as I template out examples that I have.

**Comment by yjyao** [comment]
that's ok. this change focuses only on the title. it's possible to use the same `\maketitle` while having different body layouts in different documents. we could make the types of pleading options but for now let's leave it open as `\title{whatever you want}`?

**Pull request merged**
